// Copyright (c) 2026, exacuer and contributors
// For license information, please see license.txt

frappe.query_reports["Sample Request Trend"] = {
	filters: [
		{
			fieldname: "from_date",
			label: __("From Date"),
			fieldtype: "Date",
			default: erpnext.utils.get_fiscal_year(frappe.datetime.get_today(), true)[1],
			reqd: 1,
		},
		{
			fieldname: "to_date",
			label: __("To Date"),
			fieldtype: "Date",
			default: erpnext.utils.get_fiscal_year(frappe.datetime.get_today(), true)[2],
			reqd: 1,
		},
		{
			fieldname: "periodicity",
			label: __("Periodicity"),
			fieldtype: "Select",
			options: ["Monthly", "Quarterly", "Yearly"],
			default: "Monthly",
			reqd: 1,
		},
		{
			fieldname: "date_based_on",
			label: __("Date Based On"),
			fieldtype: "Select",
			options: ["Created Date", "Dispatch Date", "Document Creation"],
			default: "Created Date",
			reqd: 1,
		},
		{
			fieldname: "customer",
			label: __("Customer"),
			fieldtype: "Link",
			options: "Customer",
		},
		{
			fieldname: "customer_group",
			label: __("Customer Group"),
			fieldtype: "Link",
			options: "Customer Group",
		},
		{
			fieldname: "sample_type",
			label: __("Sample Request Type"),
			fieldtype: "Link",
			options: "Sample Type",
		},
		{
			fieldname: "approval_status",
			label: __("Approval Status"),
			fieldtype: "Select",
			options: [
				"",
				"Draft",
				"Pending for Technical Approval",
				"Pending for CEO Approval",
				"Pending for RM Approval",
				"Pending for Admin CRM Approval",
				"Approved by RM",
				"Approved by Admin CRM",
				"Approved by CEO",
				"Technical Approved",
				"Technical Revised",
				"Technical Rejected",
				"Opened",
				"Approved",
				"Rejected",
				"Revised",
				"Dispatched",
				"Delivery Note",
				"Product Trial Created",
				"Hold",
				"Reopen",
				"Cancelled",
			],
		},
		{
			fieldname: "region",
			label: __("Region"),
			fieldtype: "Data",
		},
		{
			fieldname: "territory",
			label: __("Territory"),
			fieldtype: "Data",
		},
		{
			fieldname: "city",
			label: __("City"),
			fieldtype: "Data",
		},
		{
			fieldname: "creator",
			label: __("Creator"),
			fieldtype: "Link",
			options: "User",
		},
		{
			fieldname: "item_code",
			label: __("Item"),
			fieldtype: "Link",
			options: "Item",
		},
	],
};
